blank_issues_enabled: true
contact_links:
  - name: Request a new library
    url: https://github.com/cdnjs/packages/issues/new?assignees=&labels=%F0%9F%8F%B7+Library+Request&template=library-request.yml&title=Add%3A+xxx
    about: If you are looking to request a new library, please do so in the cdnjs/packages repository!
    
  - name: Request a library update
    url: https://github.com/cdnjs/packages/issues/new?assignees=&labels=%F0%9F%93%A6+Update+Request&template=update-request.yml&title=Update%3A+xxx
    about: Is a library missing new versions? Please make a request for our team to update it in the cdnjs/packages repository!
